# Generated by Django 3.1.7 on 2021-06-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissionPost',
            fields=[
                ('mission_id', models.AutoField(primary_key=True, serialize=False)),
                ('mission_title', models.CharField(max_length=100)),
                ('post_author', models.CharField(max_length=100)),
                ('mission_content', models.CharField(max_length=500)),
                ('mission_date', models.DateField()),
                ('post_thumbnail', models.ImageField(default='', upload_to='')),
            ],
        ),
    ]
