# Generated by Django 3.1.7 on 2021-06-24 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missionpost',
            old_name='post_author',
            new_name='mission_site',
        ),
    ]
