# Generated by Django 3.1.7 on 2021-06-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210624_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionpost',
            name='mission_type',
            field=models.CharField(blank=True, choices=[('l', 'LEO'), ('g', 'GEO'), ('i', 'Interplanetary'), ('h', 'Human-Spaceflight')], max_length=50),
        ),
    ]
