# Generated by Django 3.1.7 on 2021-06-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_missionpost_mission_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionpost',
            name='mission_type',
            field=models.CharField(blank=True, choices=[('leo', 'LEO'), ('geo', 'GEO'), ('interlanetary', 'Interplanetary'), ('human', 'Human-Spaceflight')], max_length=50),
        ),
    ]
