# Generated by Django 3.1.7 on 2021-06-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210627_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionpost',
            name='mission_type',
            field=models.CharField(blank=True, choices=[('leo', 'LEO'), ('geo', 'GEO'), ('interplanetary', 'Interplanetary'), ('human', 'Human-Spaceflight')], max_length=50),
        ),
    ]
