# Generated by Django 3.1.7 on 2021-06-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210627_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spacecraft',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),

            ],
        ),
    ]
