# Generated by Django 3.1.7 on 2021-07-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210702_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='event_link',
            field=models.URLField(),
        ),
    ]
