# Generated by Django 3.1.7 on 2021-07-02 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210702_1548'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timeline',
        ),
    ]
