# Generated by Django 3.1.7 on 2021-07-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_delete_timeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_title', models.CharField(max_length=100)),
                ('event_content', models.CharField(max_length=500)),
                ('event_link_content', models.CharField(max_length=100)),
                ('event_link', models.URLField()),
            ],
        ),
    ]
