# Generated by Django 3.1.7 on 2021-07-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='event_side',
            field=models.CharField(blank=True, choices=[('left', 'left'), ('right', 'right')], max_length=50),
        ),
    ]
