# Generated by Django 3.1.7 on 2021-07-04 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_timeline_event_side'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='event_side',
        ),
    ]
