# Generated by Django 3.1.7 on 2021-07-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_timeline_event_side'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rocket',
            fields=[
                ('rocket_id', models.AutoField(primary_key=True, serialize=False)),
                ('rocket_name', models.CharField(max_length=500)),
                ('rocket_subheading', models.CharField(max_length=500)),
                ('rocket_stat1_name', models.CharField(max_length=500)),
                ('rocket_stat1_value', models.IntegerField()),
                ('rocket_stat2_name', models.CharField(max_length=500)),
                ('rocket_stat2_value', models.IntegerField()),
                ('rocket_stat3_name', models.CharField(max_length=500)),
                ('rocket_stat3_value', models.IntegerField()),
                ('rocket_info', models.TextField(max_length=1000)),
                ('rocket_render', models.TextField(max_length=1000)),
                ('rocket_height', models.IntegerField()),
                ('rocket_dia', models.IntegerField()),
                ('rocket_stages', models.IntegerField()),
                ('rocket_lf_mass', models.IntegerField()),
                ('rocket_leo', models.IntegerField()),
                ('rocket_gto', models.IntegerField()),
                ('rocket_stage1_name', models.CharField(max_length=500)),
                ('rocket_stage1_info', models.TextField(max_length=1000)),
                ('rocket_stage1_engine', models.CharField(max_length=500)),
                ('rocket_stage1_fuel', models.CharField(max_length=500)),
                ('rocket_stage1_maxThrust', models.CharField(max_length=500)),
                ('rocket_stage2_name', models.CharField(max_length=500)),
                ('rocket_stage2_info', models.TextField(max_length=1000)),
                ('rocket_stage2_engine', models.CharField(max_length=500)),
                ('rocket_stage2_fuel', models.CharField(max_length=500)),
                ('rocket_stage2_maxThrust', models.CharField(max_length=500)),
                ('rocket_stage3_name', models.CharField(max_length=500)),
                ('rocket_stage3_info', models.TextField(max_length=1000)),
                ('rocket_stage3_engine', models.CharField(max_length=500)),
                ('rocket_stage3_fuel', models.CharField(max_length=500)),
                ('rocket_stage3_maxThrust', models.CharField(max_length=500)),
                ('rocket_stage4_name', models.CharField(max_length=500)),
                ('rocket_stage4_info', models.TextField(max_length=1000)),
                ('rocket_stage4_engine', models.CharField(max_length=500)),
                ('rocket_stage4_fuel', models.CharField(max_length=500)),
                ('rocket_stage4_maxThrust', models.CharField(max_length=500)),
            ],
        ),
    ]
