# Generated by Django 3.1.7 on 2021-07-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210704_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='rocket',
            name='rocket_code',
            field=models.CharField(default='na', max_length=500),
            preserve_default=False,
        ),
    ]
