# Generated by Django 3.1.7 on 2021-07-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210704_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='rocket',
            name='rocket_variant_thumb',
            field=models.ImageField(default='', upload_to='uploads/'),
        ),
    ]
