# Generated by Django 3.1.7 on 2021-07-04 11:59

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rocket_rocket_variant_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='rocket',
            name='rocket_launchVideo',
            field=tinymce.models.HTMLField(default='NA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rocket',
            name='rocket_overview_thumb',
            field=models.ImageField(default='', upload_to='uploads/'),
        ),
    ]
