# Generated by Django 3.1.7 on 2021-07-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20210704_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='rocket',
            name='rocket_stage1_menu_name',
            field=models.CharField(default='na', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rocket',
            name='rocket_stage2_menu_name',
            field=models.CharField(default='na', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rocket',
            name='rocket_stage3_menu_name',
            field=models.CharField(default='na', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rocket',
            name='rocket_stage4_menu_name',
            field=models.CharField(default='na', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rocket',
            name='rocket_stage4_show',
            field=models.CharField(choices=[('true', True), ('false', False)], default=True, max_length=10),
            preserve_default=False,
        ),
    ]
