# Generated by Django 3.1.7 on 2021-07-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20210709_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='mission_thumb1',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='mission_thumb2',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='mission_thumb3',
        ),
        migrations.AddField(
            model_name='mission',
            name='mission_thumbs',
            field=models.FileField(default='', upload_to='uploads/mission'),
        ),
    ]
