# Generated by Django 3.1.7 on 2021-07-09 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20210709_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='mission_thumbs',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='MissionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='uploads/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.mission')),
            ],
        ),
    ]
