# Generated by Django 3.1.7 on 2021-07-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20210709_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='mission_location',
        ),
        migrations.AddField(
            model_name='mission',
            name='mission_site',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='mission_type',
            field=models.CharField(blank=True, choices=[('leo', 'LEO'), ('geo', 'GEO'), ('interplanetary', 'Interplanetary'), ('human', 'Human-Spaceflight')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_title',
            field=models.CharField(max_length=100),
        ),
    ]
