# Generated by Django 3.1.7 on 2021-07-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20210709_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='post_thumbnail',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
