# Generated by Django 3.1.7 on 2021-07-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_mission_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rocket',
            name='rocket_launchVideo',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='rocket',
            name='rocket_render',
            field=models.TextField(max_length=2000),
        ),
    ]
